"""
Voice Service

Provides intent classification and conversational response generation
for voice-based assessments. Sits between the WebSocket route and the
assessment pipeline to detect whether the student is answering, asking
for clarification, requesting a repeat, or asking a topic question.

Only confirmed answer attempts are forwarded to the assessment pipeline.
Everything else gets a conversational instructor response.

ALL responses are generated by the LLM — no hardcoded strings.
Conversation history is injected into all prompts so the LLM can adapt.
"""

import json
import logging
from dataclasses import dataclass
from enum import Enum

from app.services.llm_service import llm_service

logger = logging.getLogger(__name__)


class StudentIntent(str, Enum):
    ANSWER_ATTEMPT = "answer_attempt"
    CLARIFICATION_REQUEST = "clarification_request"
    REPEAT_REQUEST = "repeat_request"
    TOPIC_QUESTION = "topic_question"
    PROCEED_REQUEST = "proceed_request"
    OFF_TOPIC = "off_topic"


@dataclass
class ClassificationResult:
    intent: StudentIntent
    confidence: float  # 0.0–1.0 (informational)


# ── Prompts ───────────────────────────────────────────────────────────

CLASSIFICATION_PROMPT = """You are classifying a student's speech during an oral viva (conceptual understanding assessment).

CURRENT QUESTION BEING ASKED: {question_text}

STUDENT SAID: "{student_text}"
{conversation_history}
Classify the student's intent as exactly ONE of:
- answer_attempt: Student is trying to answer or explain their understanding of the current question (even partially, vaguely, or incorrectly)
- clarification_request: Student wants the question explained differently, says they don't understand, or is confused
- repeat_request: Student wants the question repeated or said again
- topic_question: Student is asking a related conceptual question about the topic
- proceed_request: Student wants to move on, skip, or hear the next question (e.g. "next question", "move on", "continue", "skip", "let's go")
- off_topic: Student said something completely unrelated to the assessment

IMPORTANT: If the student repeatedly expresses confusion (e.g. "I don't understand", "I still don't get it") even after previous clarification attempts, classify as "clarification_request" — NOT as "answer_attempt". Expressions of confusion are NEVER answers.

Return ONLY valid JSON: {{"intent": "...", "confidence": 0.95}}"""


CONVERSATIONAL_RESPONSE_PROMPT = """You are a friendly, patient instructor during an oral viva (conceptual understanding check).
The student is a BEGINNER. Speak simply and encouragingly, like talking to someone new to programming.

CURRENT QUESTION: {question_text}
STUDENT SAID: "{student_text}"
STUDENT INTENT: {intent}
{conversation_history}
YOUR TASK based on intent:

- If "clarification_request": Help the student understand what the question is asking WITHOUT revealing the answer. Rephrase the concept in simpler terms. If you've already clarified before (see conversation history), try a COMPLETELY DIFFERENT approach — use a different analogy or angle. Be encouraging. 2-3 sentences max.

- If "repeat_request": Acknowledge their request warmly and let them know you'll repeat the question. 1 sentence max.

- If "topic_question": Give a brief, helpful response that deepens their understanding. Guide their thinking without giving away the answer. Then gently redirect back to the question. 2-3 sentences max.

- If "off_topic": Gently redirect the student back to the assessment. Be friendly, not stern. 1-2 sentences max.

- If "proceed_request": Acknowledge their wish to move on. 1 sentence max.

RULES:
- Keep responses SHORT (1-3 sentences)
- Use everyday language — no technical jargon
- Be warm and encouraging — never make the student feel bad
- NEVER reveal the answer to the assessment question
- If conversation history shows you already explained something, try a DIFFERENT approach

Return ONLY your response text, nothing else."""


# ── Service ───────────────────────────────────────────────────────────

class VoiceService:
    """Intent classification and conversational response generation."""

    @staticmethod
    def _parse_classification(raw: str) -> ClassificationResult:
        """Parse LLM JSON classification. Falls back to ANSWER_ATTEMPT on any error."""
        try:
            text = raw.strip()
            start = text.find("{")
            end = text.rfind("}") + 1
            if start == -1 or end == 0:
                return ClassificationResult(
                    intent=StudentIntent.ANSWER_ATTEMPT, confidence=0.0
                )
            data = json.loads(text[start:end])
            intent = StudentIntent(data["intent"])
            confidence = float(data.get("confidence", 0.8))
            return ClassificationResult(intent=intent, confidence=confidence)
        except (json.JSONDecodeError, ValueError, KeyError):
            return ClassificationResult(
                intent=StudentIntent.ANSWER_ATTEMPT, confidence=0.0
            )

    def classify_intent(
        self,
        student_text: str,
        question_text: str,
        conversation_history: str = "",
    ) -> ClassificationResult:
        """
        Classify student speech intent via LLM. SYNCHRONOUS — call via run_in_executor.

        Falls back to ANSWER_ATTEMPT if anything goes wrong.
        """
        history_block = ""
        if conversation_history:
            history_block = f"\n{conversation_history}\n"

        try:
            raw = llm_service.generate(
                prompt=CLASSIFICATION_PROMPT.format(
                    question_text=question_text,
                    student_text=student_text,
                    conversation_history=history_block,
                ),
                temperature=0.1,
                max_output_tokens=100,
                num_predict=100,
            )
            result = self._parse_classification(raw)
            logger.debug(
                "LLM classified as %s (%.0f%%): %s",
                result.intent, result.confidence * 100, student_text[:80],
            )
            return result
        except Exception as e:
            logger.error("Intent classification failed: %s", e)
            return ClassificationResult(
                intent=StudentIntent.ANSWER_ATTEMPT, confidence=0.0
            )

    def generate_conversational_response(
        self,
        intent: StudentIntent,
        student_text: str,
        question_text: str,
        conversation_history: str = "",
    ) -> str:
        """
        Generate an instructor-like response for non-answer intents. SYNCHRONOUS.

        ALL responses are generated by the LLM — no hardcoded strings.
        Conversation history is included so the LLM can adapt its approach.
        """
        history_block = ""
        if conversation_history:
            history_block = f"\n{conversation_history}\n"

        try:
            raw = llm_service.generate(
                prompt=CONVERSATIONAL_RESPONSE_PROMPT.format(
                    question_text=question_text,
                    student_text=student_text,
                    intent=intent.value,
                    conversation_history=history_block,
                ),
                temperature=0.5,
                max_output_tokens=300,
                num_predict=300,
            )
            text = raw.strip().strip('"').strip("'")
            if text:
                return text
        except Exception as e:
            logger.error("Conversational response generation failed: %s", e)

        # Minimal fallback — only used if the LLM call itself fails
        return "Let me help you with that. Let's take another look at the question."


# Singleton
voice_service = VoiceService()
